markdown: redcarpet

redcarpet:
  extensions: ['tables']

highlighter: pygments

title: Desenvolvedor Ruby e Javascript - Saulo Santiago
description: Desenvolvedor Ruby e Javascript, apaixonado por fazer produtos digitais incriveis
paginate: 10
paginate_path: /pagina/:num/
permalink: pretty
url: http://saulosantiago.js.org

social:
  twitter:
    username: SSILVASANTIAGO

pages_list:
  About:
    url: http://saulosantiago.com.br
    name: About
  Ruby:
    url: /ruby
    name: Ruby
  JS:
    url: /javascript
    name: Javascript
  SEO:
    url: /seo
    name: SEO
  Git:
    url: /git
    name: Git
  Feed:
    url: /feed.xml
    name: Feed

assets:
  cache: true
  js_compressor:  uglifier
  css_compressor: sass
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/stylesheets
    - _vendor/javascripts

gems:
  - jekyll-assets
  - jekyll-sitemap
  - redcarpet
  - uglifier
