markdown: redcarpet

redcarpet:
  extensions: ['tables']

highlighter: pygments

title: 'Saulo Santiago'
description: 'Web developer se aventurando em escrever posts sobre tecnologia.'
tagline: 'Javascript, Ruby, Rails, Java, Backbone, Marionette'

paginate: 10
paginate_path: '/pagina/:num/'
permalink: pretty
url: https://saulosilva.github.io

pages_list:
  About: '/about'
  Ruby: '/ruby'
  JS: '/js'
  Feed: '/atom.xml'

assets:
  cache: false
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/stylesheets
    - _vendor/javascripts