markdown: redcarpet

redcarpet:
  extensions: ['tables']

highlighter: pygments

title: Saulo Santiago
description: Desenvolvedor Ruby e Javascript. Trabalho há 6 anos com sistemas web. Meu maior combustível é a cafeína. E se aventurando em escrever posts sobre tecnologia.
tagline: 'Javascript, Ruby, Rails, Java, Backbone, Marionette'

paginate: 10
paginate_path: /pagina/:num/
permalink: pretty
url: https://saulosilva.github.io

social:
  twitter:
    username: SSILVASANTIAGO

pages_list:
  About:
    url: http://saulosantiago.com.br
    name: About
    class_name: about
    ico_name: about-ico
  Ruby:
    url: /ruby
    name: Ruby
    class_name: ruby
    ico_name: ruby-ico
  JS:
    url: /js
    name: Js
    class_name: js
    ico_name: js-ico
  Feed:
    url: /feed.xml
    name: Feed
    class_name: feed
    ico_name: feed-ico

assets:
  cache: false
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/stylesheets
    - _vendor/javascripts