markdown: redcarpet

redcarpet:
  extensions: ['tables']

highlighter: pygments

title: Saulo Santiago
description: Desenvolvedor Ruby e Javascript. Trabalho há 6 anos com sistemas web. Meu maior combustível é a cafeína. E se aventurando em escrever posts sobre tecnologia.
paginate: 10
paginate_path: /pagina/:num/
permalink: pretty
url: https://saulosilva.github.io

social:
  twitter:
    username: SSILVASANTIAGO

pages_list:
  About:
    url: http://saulosantiago.com.br
    name: About
  Ruby:
    url: /ruby
    name: Ruby
  JS:
    url: /javascript
    name: Javascript
  Feed:
    url: /feed.xml
    name: Feed

assets:
  cache: false
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/stylesheets
    - _vendor/javascripts

gems:
  - jekyll-assets
  - redcarpet