source 'https://rubygems.org'
gem 'github-pages'
gem 'awestruct'
gem 'redcarpet'
gem 'rake'
gem 'uglifier'
gem 'jekyll-assets', '0.14.0'
gem 'jekyll-sitemap'
gem 'travis', '1.7.6'

gem 'timers', '4.0.1'