source 'https://rubygems.org'

gem 'github-pages',   '39'
gem 'awestruct',      '0.5.3'
gem 'redcarpet',      '3.3.2'
gem 'rake',           '10.4.2'
gem 'uglifier',       '2.7.2'
gem 'jekyll-assets',  '1.0'
gem 'jekyll-sitemap', '0.8.1'
gem 'travis',         '1.7.6'
gem 'timers',         '4.0.1'
gem 'activesupport',  '4.2.6'
